- en/contributing/build.md
This was wrong and would put you in an empty folder in docker.
> build: fix Dronecore -> DroneCore

- en/examples/fly_mission.md
Related to https://github.com/dronecore/DroneCore/pull/83.
> examples: the fly_mission cpp file was renamed

- book.json
- en/guide/connections.md
- en/guide/taking_off_landing.md
- en/guide/toolchain.md
This adds menu bar across top of page.
> Switch to using new dronecore theme

- en/contributing/dev_logging.md
This captures docs changes associated with https://github.com/dronecore/DroneCore/pull/125
> Make debug printfs green

- en/contributing/build.md
- Updated the CURL version.
- Added cmake to requirements.
- Moved from VS2015 to VS2017.
> Update Windows build

- en/contributing/build.md
- en/contributing/documentation.md
- en/guide/toolchain.md
This documents  generate_docs.sh, added in https://github.com/dronecore/DroneCore/pull/166
> Replace make docs with generate_docs.sh

- en/examples/README.md
- en/guide/toolchain.md
This follows fix in https://github.com/dronecore/DroneCore/pull/178
> Update Windows app build instructions following retesting

- en/contributing/dev_logging.md
This adds info from https://github.com/dronecore/DroneCore/pull/194.
> Add information about message logging

- en/SUMMARY.md
- en/api_reference/classdronecore_1_1_follow_me.md
- en/api_reference/structdronecore_1_1_follow_me_1_1_config.md
- en/api_reference/structdronecore_1_1_follow_me_1_1_target_location.md
- en/guide/follow_me.md
This adds follow me guide.
This is untested. Waiting on some of the following to be looked at:
> Follow me guide

- en/contributing/plugins.md
- en/contributing/test.md
> Update integration/unit test docs

- en/README.md
- en/api_reference/classdronecore_1_1_device.md
- en/api_reference/classdronecore_1_1_device_plugin_container.md
- en/api_reference/classdronecore_1_1_follow_me.md
- en/api_reference/structdronecore_1_1_follow_me_1_1_config.md
- en/api_reference/structdronecore_1_1_follow_me_1_1_target_location.md
- en/getting_started/README.md
- en/guide/follow_me.md
- Overview already includes Gimbal so not needed.
- Also adds updated API reference.
NOTE, this breaks some direct links to API reference members. Before fixing those, I'm thinking about whether I can create a better linking strategy.
> Update overview to include FollowMe

- en/contributing/build.md
We now have multiple docker files, so instructions for building in docker need to change - as per https://github.com/dronecore/docs/issues/85#issuecomment-362283401
@julianoes This has some issues/things that don't work. I need help! Will post inline
> Updates for new docker script info

- en/contributing/code_style.md
In response to https://github.com/dronecore/DroneCore/issues/279.
> code_style: add note about exceptions

- en/getting_started/faq.md
Addresses https://github.com/dronecore/DroneCore/issues/234#issuecomment-363008920
> Make clear statement about indoor use support

- en/api_reference/classdronecore_1_1_drone_core.md
- en/api_reference/classdronecore_1_1_telemetry.md
- en/guide/connections.md
Adds docs for https://github.com/dronecore/DroneCore/pull/264
> Update docs for new add_any_connection method

- en/SUMMARY.md
- en/api_reference/README.md
- en/api_reference/classdronecore_1_1_action.md
- en/api_reference/classdronecore_1_1_device.md
- en/api_reference/classdronecore_1_1_drone_core.md
- en/api_reference/classdronecore_1_1_follow_me.md
- en/api_reference/classdronecore_1_1_gimbal.md
- en/api_reference/classdronecore_1_1_info.md
- en/api_reference/classdronecore_1_1_logging.md
- en/api_reference/classdronecore_1_1_mission.md
- en/api_reference/classdronecore_1_1_mission_item.md
- en/api_reference/classdronecore_1_1_offboard.md
- en/api_reference/classdronecore_1_1_plugin_base.md
- en/api_reference/classdronecore_1_1_telemetry.md
- en/api_reference/namespacedronecore.md
- en/api_reference/structdronecore_1_1_follow_me_1_1_config.md
- en/contributing/plugins.md
- en/examples/fly_mission.md
- en/examples/fly_mission_qgc_plan.md
- en/examples/follow_me.md
- en/examples/offboard_velocity.md
- en/examples/takeoff_and_land.md
- en/examples/transition_vtol_fixed_wing.md
- en/guide/connections.md
- en/guide/follow_me.md
- en/guide/general_usage.md
- en/guide/missions.md
- en/guide/offboard.md
- en/guide/taking_off_landing.md
- en/guide/telemetry.md
Implements https://github.com/dronecore/docs/issues/104 and https://github.com/dronecore/DroneCore/pull/290
> Update docs for global ConnectionResult and connection_result_str()

- en/api_reference/classdronecore_1_1_action.md
- en/api_reference/classdronecore_1_1_drone_core.md
- en/api_reference/classdronecore_1_1_follow_me.md
- en/api_reference/namespacedronecore.md
This is docs rebuild following changes in https://github.com/dronecore/DroneCore/pull/374
I will merge as this is same text, just re-organised.
> Fix up apiref to use gitbook notes and warnings

- en/examples/follow_me.md
- en/guide/follow_me.md
Previously you couldn't use QGC and DroneCore follow me. Now you can. This update explains how.
> Update Follow me with info about how to use with QGC

- en/SUMMARY.md
- en/api_reference/README.md
- en/api_reference/classdronecode__sdk_1_1_mission_raw.md
- en/api_reference/classdronecode__sdk_1_1_params_raw.md
- en/api_reference/namespacedronecode__sdk.md
- en/api_reference/structdronecode__sdk_1_1_mission_raw_1_1_mavlink_mission_item_int.md
- en/cpp/README.md
Note, I couldn't add passthrough plugin yet, because it does not get built.
> ApiRef: Add mission raw plugin

- en/contributing/build.md
The openssl dependency was missing.
> macOS build instructions

- en/README.md
- en/cpp/README.md
The forums now has https. Moreover, the subforum should be renamed from DroneCore to Dronecode.
> Fix discuss links and badges

- README.md
> README: correct documentation link to prevent 404

- en/contributing/build.md
Found by trying it :-) FYI @JonasVautherin
> Fix up doc build instructions

- en/contributing/build.md
@douglaswsilva: FYI
Updating the instructions to show how to build `mavsdk_server` for iOS.
> Improve instructions for iOS build

- en/guide/telemetry.md
related to issue [https://github.com/mavlink/MAVSDK/issues/996](https://github.com/mavlink/MAVSDK/issues/996)
> add note to avoid Promise already satisfied

- en/examples/README.md
- en/examples/fly_mission.md
- en/examples/fly_mission_qgc_plan.md
- en/examples/follow_me.md
- en/examples/offboard_velocity.md
- en/examples/takeoff_and_land.md
- en/examples/transition_vtol_fixed_wing.md
Signed-off-by: Omar Shrit <shrit@lri.fr>
> Move example to examples

- en/contributing/build.md
> Build fixes for Windows build

- en/guide/offboard.md
Small fix to address confusion what setpoint to set before starting offboard.
> offboard: clarify offboard start

- en/cpp/api_changes.md
> cpp: slight improvements for consistency

- en/SUMMARY.md
- en/contributing/release.md
I thought as I'm doing the release I should write the steps down.
> contributing: add page on how to release

- en/cpp/troubleshooting.md
- en/guide/general_usage.md
> Callbacks follow up

- en/cpp/troubleshooting.md
> cpp: fix link id

- en/cpp/api_changes.md
Goes with https://github.com/mavlink/MAVSDK/pull/694/.
> api_changes: describe API changes with v0.33.0

- en/contributing/code_style.md
> contributing: switch from C++11 to C++17

- assets/site/slack.svg
- book.json
- en/README.md
- Plugin order may (now) matter. This builds locally anyway.
- Also slack badge link has been broken forever. This fixes it.
> Fix slack logo and CI

- en/faq.md
I'm writing this down as @bazfp had asked me.
> Add why C++ and gRPC to FAQ

- en/SUMMARY.md
- en/cpp/examples/autopilot_server.md
- en/cpp/server_plugins.md
Added the autopilot server example page
Changed the server plugins to be a bit more useful for vehicle manufacturers
> Add autopilot server example

- en/cpp/api_changes.md
Documents https://github.com/mavlink/MAVSDK/pull/1639.
> api_changes: document library linking changes

- en/cpp/guide/build.md
As it came up in https://github.com/mavlink/MAVSDK/issues/1988.
> cpp: recommend Visual Studio 2022

- book.json
- en/cpp/api_changes.md
> Getting ready for MAVSDK v2

- en/README.md
- Slack -> Discord
- Add maintenance and support section
> Update readme/front page

- en/cpp/api_changes.md
- en/faq.md
I might add one more for changed subscriptions.
> faq: document API changes

- en/README.md
> Readme: update state of MAVSDK-Go
