mavlink/MAVSDK-docs

en/contributing/build.md
Required for Windows after testing. For Mac to list the cmake and clang dependencies.
=> Fix up instructions for building on Windows and Mac

en/contributing/build.md, en/examples/takeoff_and_land.md
This updates the build instructions for windows in line with: https://github.com/dronecore/DroneCore/pull/51/
It also removes the "Python" ish instructions - since it is not clear when those examples will appear.
=> Fix Windows build instructions

en/contributing/build.md
@julianoes This updates the instructions for building using Docker.  The main changes are that:
-  this downloads the image rather than building it in the main example. This is usually a lot faster. I still show how to build the image in a later section
- This opens a bash prompt. Main reason is that if you want to build the application then this is much easier in bash - and so are instructions: "just pretend you are on linux" :-)
- I do also show the same things you did, as sub sections.
=> Update docker instructions to use bash

en/SUMMARY.md, en/guide/README.md, en/guide/general_usage.md
@julianoes This adds the guide section and first guide topic. The first topic is supposed to include everything the main "general" knowledge you have to know to use the API - error handling, how to create the library etc. 
Not sure where instructions for the CMakeLists.txt file should live. Possibly here, but more likely in a separate doc.
=> Create guide section and add general paradigms topic

en/SUMMARY.md, en/contributing/build.md, en/guide/toolchain.md
This explains 
- the requirements for a build system (essentially anything you like, as long as it can find the libs/headers for DroneCore AND it adds the needed thread library).
- The minimum setup if you want to use cmake, based on our example code.
It does feel a little ponderous (mostly because of the relative paths), but anyone wanting to build apps is going to have to go down this path, and I think having an explanation helps.
=> Add topic explaining how to set up build files for Cpp apps

en/SUMMARY.md, en/guide/telemetry.md
This adds explanation of how to use the telemetry API. It uses just a few examples, but makes it clear that all the rest are the same, and points to the examples and integration test for more "real code".
The use cases I've tried to address are:
- Setting rate
- Reporting regular updates
- Reporting changes
- Blocking on state
@julianoes I am not particularly concerned that the code will be incorrect - more that the recommendations are not "best practise". Appreciate your review.
=> Add telemetry guide

en/contributing/build.md
The argument `--rm` automatically cleans up leftover docker containers
after you exit the docker container.
To cleanup old containers, you can also use:
```
docker system prune
```
=> build: automatically cleanup docker container

en/SUMMARY.md, en/guide/taking_off_landing.md
This adds documentation for the Action API. 
- It is named "Takeoff and Landing" as those are the main APIs, and I don't think that "Action" will necessarily be recognised by readers. 
- It refers to both sync and async APIs but only shows sync examples. IMO that makes sense as a) sync usage is much easier to understand b) will most often be used.
- I don't show examples in every case, because the APIs are consistent. So I say something like "Used in the normal way"
=> Add takeoff/landing doc - also covers other action APIs

en/SUMMARY.md, en/api_reference/README.md, en/api_reference/classdronecore_1_1_info.md, en/api_reference/structdronecore_1_1_info_1_1_product.md, en/api_reference/structdronecore_1_1_info_1_1_version.md, en/guide/device_version.md
This updates the api reference and guide for new `Info::Product` struct (and changes in `Info::Version`). Ie it is the docs that match this update: https://github.com/dronecore/DroneCore/pull/118
It may need further revision when https://github.com/dronecore/DroneCore/issues/132 is discussed.
=> Info add vendor product 118

en/contributing/code_style.md
This adds the code guidelines that were followed when DroneCore was
written. They are not set in stone and can be changed for reasons other
than taste.
=> code_style: added some code guidelines

.travis.yml, book.json, en/README.md, en/contributing/code_style.md, en/contributing/dev_logging.md, en/contributing/documentation.md, en/contributing/plugins.md, en/examples/README.md, en/examples/fly_mission.md, en/examples/offboard_velocity.md, en/examples/takeoff_and_land.md, en/getting_started/faq.md, en/guide/dronecore_extensions.md, en/guide/missions.md, en/guide/offboard.md, en/guide/taking_off_landing.md, en/guide/telemetry.md
This updates docs to:
1. Fix links from travis broken link checker. 
2. Update links to github to be relative to a variable defined in the book.json. This will allow us to point to different docs on master and develop. May need more rework, but aim is to properly support versions of dronecore source for examples and source links.
=> Fix links and specify github paths relative to variable

en/contributing/build.md
As per https://github.com/dronecore/DroneCore/issues/151#issuecomment-342921001
@julianoes Anything special need to happen/be documented to add this dependency for Windows?
=> Add libtinyxml2-dev dependency to build instructions

en/contributing/build.md, en/examples/README.md, en/examples/fly_mission.md, en/examples/offboard_velocity.md, en/examples/takeoff_and_land.md, en/guide/dronecore_extensions.md, en/guide/toolchain.md
This is first draft of doc updates for https://github.com/dronecore/DroneCore/pull/130 (as recorded in #51 ). More to come, there are open issues required to complete this.
- Examples require `sudo`: https://github.com/dronecore/DroneCore/issues/156
- Examples not running: https://github.com/dronecore/DroneCore/issues/157
- Confirmed by @julianoes
=> First draft of updates for #51

en/api_reference/classdronecore_1_1_action.md, en/api_reference/classdronecore_1_1_device.md, en/api_reference/classdronecore_1_1_follow_me.md, en/api_reference/classdronecore_1_1_gimbal.md, en/api_reference/classdronecore_1_1_info.md, en/api_reference/classdronecore_1_1_logging.md, en/api_reference/classdronecore_1_1_mission.md, en/api_reference/classdronecore_1_1_offboard.md, en/api_reference/classdronecore_1_1_telemetry.md, en/contributing/plugins.md, en/examples/fly_mission.md, en/examples/fly_mission_qgc_plan.md, en/examples/follow_me.md, en/examples/offboard_velocity.md, en/examples/takeoff_and_land.md, en/examples/transition_vtol_fixed_wing.md, en/guide/device_version.md, en/guide/follow_me.md, en/guide/missions.md, en/guide/offboard.md, en/guide/taking_off_landing.md, en/guide/telemetry.md, en/guide/using_plugins.md
This fixes up docs to match PR https://github.com/dronecore/DroneCore/pull/316 (ie addresses #106 )
@shakthi-prashanth-m Can you please sanity check this.
=> Fix - Choose reference over pointer

LICENSE
This allows Github to display license text up to. Even better, it means we are consistent across all Dronecode projects for our CC license.
=> Update CC license to exact text for other Dronecode projects

en/api_reference/classdronecore_1_1_drone_core.md, en/api_reference/namespacedronecore.md, en/examples/README.md, en/examples/fly_mission.md, en/examples/fly_mission_qgc_plan.md, en/examples/follow_me.md, en/examples/offboard_velocity.md, en/examples/takeoff_and_land.md, en/examples/transition_vtol_fixed_wing.md, en/guide/connections.md
Replaces #117
This updates reference following changes in: https://github.com/dronecore/DroneCore/pull/375 and Further changes needed as result of https://github.com/dronecore/DroneCore/pull/394
There are some outstanding questions:
* https://github.com/dronecore/DroneCore/pull/375#discussion_r185671513 - no default connection
* https://github.com/dronecore/DroneCore/pull/375/files#r185674108 - missing ref
* https://github.com/dronecore/DroneCore/issues/380
This changes some APIs so the changed references will need to be updated in example code etc. 
Also in trying the examples we say: 
> The simulator broadcasts to the standard PX4 UDP port for connecting to offboard APIs (14540). The examples connect to this port by default, using DroneCore::add_udp_connection()."
In fact only some of …
=> Update connections documentation

en/guide/toolchain.md
This is an attempt to simplify the instructions how to include the
Dronecode SDK headers and how to link against the library.
Also, this specifies that applications linking to the SDK don't need to
be written in C++11 but rather C++11 or later.
=> toolchain: improve instructions how to build app

en/getting_started/faq.md
I think it is worth making clear that PX4 is the supported flight stack and that we'll take other contributions, but only if accompanied by testing and maintenance.
=> Add "what flight stacks supported" FAQ

en/contributing/build.md
@JonasVautherin This is first shot at building backend docs. Can you add instructions for macOS too.
Is there any need to do an "install" for this too? I.e what are the semantics - if I build with backend and then do install is that installed as well?
=> Add build backend instructions for Ubuntu

en/contributing/test.md, en/examples/README.md
With master and 1.9.x it is `px4_sitl` instead of `posix`.
=> Fix PX4 SITL command

en/contributing/build.md, en/contributing/code_style.md, en/contributing/test.md
Update the C++ docs, now showing how to build using cmake.
@hamishwillee: I made the edits with gitbook-editor, and it somehow made some changes (like escaping parentheses `\(`). Should I revert that or is it fine to keep them?
@julianoes: I removed the build section about Docker, as I am not sure if it is up-to-date and I believe it is not so relevant (people who may want to do that would go check our scripts, and it is noise for people who don't know docker). I can revert it if you want.
=> Update C++ docs following build system changes

en/README.md, en/contributing/build.md, en/cpp/README.md, en/examples/README.md, en/getting_started/README.md
- Remove flight-stack specifics.
- Add python link to getting started. Clarify that it had/does everything.
- General changes to make it clear that C library doesn't need to be built on ubuntu/fedora
=> Improve intro branding. Add status info

en/examples/README.md
This adds links and summary text for all examples into the example entry point page. I also alphabetized the examples.
I would have liked to create full docs for each, but this is a good start for anyone browsing.
This flows out of a recent query about how to use multiple drones.
@julianoes What's the difference between the two multiple drone examples? Feel free to edit the text directly and merge.
=> Examples: Create into/links for all examples

en/examples/README.md
Fixes a typo for the documentation text misspelling ``example``
=> Fixed typo for calibration example text

en/contributing/test.md
The integration_tests directory had been moved to src a while ago.
=> contributing: fix path of integration_tests_runner

en/contributing/code_style.md
This also adds how to install clang-format version 9 and how to run the style fix using docker.
=> contributing: more help how to fix style

en/examples/README.md, en/examples/follow_me.md
1. A link on example page's follow-me category, it's link previously went to offboard doc.
2. Link on Follow-me's documentation linked towards fly_mission doc.
Fixed two links! Great Doc, helped a lot!
Just curious, some links inside the .md files use notations like `https://github.com/mavlink/MAVSDK/**blob**/{{ book.github_branch }}/examples/follow_me/` but others use `https://github.com/mavlink/MAVSDK/**tree**/{{ book.github_branch }}/examples/fly_multiple_drones`. Are there differences between 'blob' and a 'tree'?
=> Fix wrong links in follow_me and examples documentation

en/examples/fly_mission.md, en/examples/fly_mission_qgc_plan.md, en/examples/follow_me.md, en/examples/offboard_velocity.md, en/examples/takeoff_and_land.md, en/examples/transition_vtol_fixed_wing.md, en/guide/taking_off_landing.md
Updates examples to use the new form of success (i.e. match to https://github.com/mavlink/MAVSDK/pull/1024)
Note this is just a search/replace. I didn't make sure the examples are otherwise up to date, so possibly there could have been other missed changes.
=> Action::Result::SUCCESS > Success

en/SUMMARY.md, en/cpp/README.md, en/cpp/api_changes.md
This adds a page to help with transitioning from one version to the next version.
This is work in progress as we move to auto-generation of the C++ part:
https://github.com/mavlink/MAVSDK/pull/1017
https://github.com/mavlink/MAVSDK/pull/1028
https://github.com/mavlink/MAVSDK/pull/1029
https://github.com/mavlink/MAVSDK/pull/1036
=> Add API changes notes

en/SUMMARY.md, en/contributing/plugins.md, en/cpp/README.md, en/examples/README.md, en/examples/fly_mission.md, en/examples/fly_mission_qgc_plan.md, en/examples/follow_me.md, en/examples/offboard_velocity.md, en/examples/takeoff_and_land.md, en/examples/transition_vtol_fixed_wing.md, en/guide/connections.md, en/guide/follow_me.md, en/guide/general_usage.md, en/guide/missions.md, en/guide/offboard.md, en/guide/taking_off_landing.md, en/guide/telemetry.md
Prior to creating the 0.25 release
@julianoes This fixes all the broken anchor URLs. I have tried to fix up methods and code fragments to new names if that was obvious from the usage. This also replaces the example code in the examples.
All that should be "OK".
BUT we (you guys) need to review and update the docs like general usage, connections etc in the guide and sanity check them. Lots changed over time that may well not have been updated by me. That stuff is the basic getting started with C++ so it needs to be right. Can you update.
Feel free to merge this PR for now if it si OK.
=> Fix up links and examples in develop

en/guide/general_usage.md
@julianoes @JonasVautherin OK, this fixes https://github.com/mavlink/MAVSDK-docs/issues/206
The idea is to provide concrete examples of the connection strings that we can point people to. I wasn't sure the "right" place to put this because we want to link to this from Python and whatever.  Hence here in "usage" so it is one of the first things you run into. We could alternatively have in the [Monitoring Port](https://mavsdk.mavlink.io/develop/en/guide/connections.html) section?
Is there a better place? Are there "common" usage paradigms we should be documenting for all libraries at a top level? If so, this would go there (but I would need your help to characterise what these paradigms might be).
Please check the macOS example lines. I THINK both just use a USB device ID for the port. …
=> Add connection string information

en/SUMMARY.md, en/cpp/README.md, en/cpp/troubleshooting.md
This explains what not to do in callbacks and how to debug related issues.
Goes together with https://github.com/mavlink/MAVSDK/pull/1143.
=> cpp: add troubleshooting page

en/releases/README.md
Alternative to https://github.com/mavlink/MAVSDK-docs/pull/217
@JonasVautherin I think there is value in outlining where releases can be found in one place, and also making it clear that the release cycle for the different runtimes is not co-ordinated. So rather than deleting the page, I deleted the "in beta" note.
We could add this back "per runtime". 
What else would we say?
=> Update releases info to be accurate

en/getting_started/installation.md
Since Linux ARM platforms are [supported ](https://pypi.org/project/mavsdk/#files) now, there is no need to raise this note for MAVSDK-Python installation.
=> Remove the warning for linux arm support of mavsdk-python

en/contributing/build.md, en/contributing/plugins.md
- BUILD_MAVSDK_SERVER has replaced BUILD_BACKEND.
- note about protoc_gen_mavsdk
=> contributing: various fixes

en/SUMMARY.md
My original intention was to update this to say "Dronecode Foundation Shortcuts," which caused the text to create a second line, making it look terrible. I instead opted for removing "Dronecode" altogether and leaving it as "Helpful Shortcuts."
=> Navigation: Helpful Shortcuts (remove Dronecode)

en/README.md
Fixes the reference to Dronecode, we should be calling it the Dronecode Foundation everywhere.
=> README: Update reference to DF

book.json, en/contributing/release.md
We should not create new branches, doc entries for patch releases because by definition these should only include bugfixes and no API changes.
=> contributing: omit branches for bugfix releases

en/cpp/api_changes.md
To import QGC missions, you now need to use MissionRaw instead of Mission.
Thanks @mcsauder!
=> api_changes: add note about QGC plan import change

book.json, en/cpp/api_reference/classmavsdk_1_1_action.md, en/cpp/api_reference/classmavsdk_1_1_camera.md, en/cpp/api_reference/classmavsdk_1_1_ftp.md, en/cpp/api_reference/classmavsdk_1_1_geofence.md, en/cpp/api_reference/classmavsdk_1_1_gimbal.md, en/cpp/api_reference/classmavsdk_1_1_info.md, en/cpp/api_reference/classmavsdk_1_1_log_files.md, en/cpp/api_reference/classmavsdk_1_1_mission.md, en/cpp/api_reference/classmavsdk_1_1_mission_raw.md, en/cpp/api_reference/classmavsdk_1_1_param.md, en/cpp/api_reference/classmavsdk_1_1_tune.md, en/cpp/api_reference/namespacemavsdk.md, en/cpp/api_reference/structmavsdk_1_1_info_1_1_identification.md, en/cpp/api_reference/structmavsdk_1_1_mission_1_1_mission_item.md
Howdy @julianoes 
All I've done is run the generator and copy in the reference.
The actuator documentation looks "insufficient" - there is no information about the values that get passed as arguments. Any chance of at least a cross link to mavlink docs for SET_ACTUATOR? Further, can I have an example to use for updating https://docs.px4.io/master/en/payloads/#mavsdk-example-script and then we might link to that? We need that anyway.
Feel free to merge this as-is for now and we can continue the discussion.
PS Generator modification came out of this: https://github.com/mavlink/MAVSDK/pull/1453
=> Update API ref to 0.40

en/cpp/server_plugins.md
Links were using `..` instead of `.` causing them to point to the wrong relative directory.
=> Fix server plugin page links

en/cpp/guide/build.md
This adds a section how the MAVLink headers can be replaced, and how a custom dialect can be used.
=> cpp: how to swap MAVLink headers and dialects

en/faq.md
Hi,
I started doing some typo fixes and ended up cleaning up a bit more. Please note that I removed the entire **"Why is MAVSDK written in C++?"** question and answer due to the very similar question and answer **"Why was the core of the SDK written in C++?"**.
Please make changes if you see things you don't agree with, or just let me know and I will do it instead.
All the best,
Christoffer
=> Fix typos and improve formulations in FAQ

en/README.md, en/cpp/api_changes.md, en/cpp/contributing/plugins.md, en/cpp/examples/autopilot_server.md, en/cpp/guide/offboard.md, en/faq.md
This is the result of running codespell on the docs like:
```
codespell -s -L "ned"
```
Other than a deep desire to change `PositionNed ==> positioned` nothing found in protos. 
Docs had a few small typos, all fixed.
From which I can only assume that there is spell checking going on already :-)
=> Run codespell on docs

en/cpp/guide/telemetry.md
Found a small error in the documentation: telemetry.subscribe_all_ok() doesn't exist, this was probably meant to be the telemetry.subscribe_health_all_ok() method.
=> Update telemetry.md; telemetry.subscribe_all_ok() does not exist

en/cpp/guide/build.md
The part how to actually use MAVSDK installed locally was missing.
=> cpp: explain how to use local install

en/cpp/quickstart.md
- add hint to first remove old mavsdk version
- update example with the naming syntax of one of the latest releases
=> Update quickstart.md for Linux install

en/cpp/guide/build_mavsdk_server.md
Somehow this was left out.
WIP for now. We might change it to static to avoid missing DLLs when running it.
=> guide: add missing build for Windows

en/cpp/contributing/plugins.md
https://mavsdk.mavlink.io/main/en/cpp/contributing/plugins.html
- Updated Folder diagram to keep it up to date with MAVSDK repository (as plugins moved into src/mavsdk)
- Update *Note* part since in the doc the 'Note' part gets replaced with an image, to make it read more natural
=> Update plugins page to be up to date

en/cpp/guide/build.md
1. Understanding MAVSDK (Proto) Build process is hard
2. There can be subtle issues where the `protoc-gen-mavsdk` python library is not up to date and can create undesirable results when files get generated with the `tools/generate_from_protos.sh` command
- It resulted in this PR / troubleshooting process : https://github.com/mavlink/MAVSDK/pull/1779
4. Decoupling the `protoc` and `protoc-gen-mavsdk` part and clearly explaining what is doing what is needed
> Work in progres
=> Improve Proto generation & Build document

book.json
=> Make label on front of version v2 say v2 - not main

en/cpp/guide/follow_me.md, en/cpp/guide/missions.md, en/cpp/guide/offboard.md, en/cpp/guide/taking_off_landing.md, en/cpp/guide/telemetry.md, en/cpp/guide/using_plugins.md
The sections regarding linking of plugin library were removed from the taking_off_landing.md, telemetry.md, follow_me.md, missions.md, offboard.md, using_plugins.md documentation files:
With recent versions of MAVSDK, you only need MAVSDK::mavsdk and hence these sections are removed.
=> Remove redundant plugin library linking instructions from documentation

en/cpp/guide/connections.md, en/cpp/guide/follow_me.md, en/cpp/guide/missions.md, en/cpp/guide/offboard.md, en/cpp/guide/taking_off_landing.md, en/cpp/guide/telemetry.md
- Updated MAVSDK instantiation to comply with V2 API changes across the following documentation files: missions.md, connections.md, follow_me.md, telemetry.md, offboard.md, taking_off_landing.md.
- Replaced old instantiation Mavsdk mavsdk; with the new instantiation Mavsdk mavsdk{Mavsdk::Configuration{Mavsdk::ComponentType::GroundStation}};.
- The Mavsdk class now requires a configuration to be passed as a constructor argument to specify the component type.
- Ensured all examples reflect the updated instantiation method for consistency and accuracy.
=> Update MAVSDK instantiation to new V2 API across documentation

en/cpp/api_reference/classmavsdk_1_1_mavsdk.md
This commit corrects a minor formatting issue where few entries in the description column were shifted by one row. The data is now properly aligned.
=> Fix data misalignment
